spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/mytest
      driver-class-name: org.h2.Driver
      username: sa
      password: 
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true